[platformio]
default_envs = esp32dev

; Entorno para ESP32 (DevKit V1 / NodeMCU-32S)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

; Entorno para Raspberry Pi Pico / Pico 2 W
[env:pico]
platform = raspberrypi
board = rpipico
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
